List<String> outils = [
  'Outillage métrologie',
  'Outils de fraisage',
  'Outils de tournage',
  'Outils de perçage',
  'Outils à main'
];

List<String> outilsNomImg = [
  'metrologie',
  'fraiseuse',
  'tour',
  'perceuse',
  'main'
];

List<String> categories = [
  "Mesure directe",
  "Mesure indirecte",
  "Affichage analogique",
  "Jauge d\'angle",
  "Micromètre",
  "Jauges tampon",
  "Pieds à coulisse",
];


// final String outilsData = '''[
//   {
//     "id": "1",
//     "no_inventaire": "",
//     "designation": "Microm\u00e8tre ext\u00e9rieur",
//     "dim_mm_1": "0",
//     "dim_mm_2": "15",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "Touches fine",
//     "emplacement": "Tiroir 4\/D1",
//     "etat": "Usag\u00e9",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "2",
//     "no_inventaire": "2017000000815",
//     "designation": "Microm\u00e8tre ext\u00e9rieur",
//     "dim_mm_1": "0",
//     "dim_mm_2": "25",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "Touches fine",
//     "emplacement": "Tiroir 4\/AB3",
//     "etat": "Neuf",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "3",
//     "no_inventaire": "",
//     "designation": "Microm\u00e8tre ext\u00e9rieur",
//     "dim_mm_1": "25",
//     "dim_mm_2": "50",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "Touches standard",
//     "emplacement": "Tiroir 4\/AB3",
//     "etat": "Neuf",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "4",
//     "no_inventaire": "",
//     "designation": "Microm\u00e8tre int\u00e9rieur",
//     "dim_mm_1": "6",
//     "dim_mm_2": "12",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "3 points de contact",
//     "emplacement": "Tiroir 4\/D56",
//     "etat": "Usag\u00e9",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "5",
//     "no_inventaire": "",
//     "designation": "Microm\u00e8tre int\u00e9rieur",
//     "dim_mm_1": "11",
//     "dim_mm_2": "20",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "3 points de contact",
//     "emplacement": "Tiroir 4\/C56",
//     "etat": "Usag\u00e9",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "6",
//     "no_inventaire": "",
//     "designation": "Verre d'interf\u00e9rence",
//     "dim_mm_1": "0",
//     "dim_mm_2": "0",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "Pour contr\u00f4le microm\u00e8tre",
//     "emplacement": "Tiroir 4\/C1",
//     "etat": "Usag\u00e9",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "7",
//     "no_inventaire": "",
//     "designation": "Comparateur \u00e0 cadran",
//     "dim_mm_1": "0",
//     "dim_mm_2": "10",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "",
//     "emplacement": "Tiroir 4\/C4",
//     "etat": "Usag\u00e9",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "8",
//     "no_inventaire": "",
//     "designation": "Comparateur \u00e0 levier",
//     "dim_mm_1": "0",
//     "dim_mm_2": "0",
//     "dim_angle_1": "-30",
//     "dim_angle_2": "30",
//     "complement": "",
//     "emplacement": "Tiroir 4\/AB4",
//     "etat": "Usag\u00e9",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "9",
//     "no_inventaire": "",
//     "designation": "Comparateur \u00e0 levier",
//     "dim_mm_1": "0",
//     "dim_mm_2": "0",
//     "dim_angle_1": "-30",
//     "dim_angle_2": "30",
//     "complement": "",
//     "emplacement": "Tiroir 4\/AB4",
//     "etat": "Usag\u00e9",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "10",
//     "no_inventaire": "",
//     "designation": "Comparateur \u00e0 affichage digital",
//     "dim_mm_1": "0",
//     "dim_mm_2": "10",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "Pour mesure sur support vertical",
//     "emplacement": "Tiroir 4\/ABCD4",
//     "etat": "Neuf",
//     "login": "cp-jeg",
//     "status": "Emprunt\u00e9"
//   },
//   {
//     "id": "11",
//     "no_inventaire": "",
//     "designation": "Comparateur \u00e0 affichage digital",
//     "dim_mm_1": "0",
//     "dim_mm_2": "10",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "Pour mesure sur support vertical",
//     "emplacement": "Tiroir 4\/ABCD4",
//     "etat": "Neuf",
//     "login": "cp-jeg",
//     "status": "Emprunt\u00e9"
//   },
//   {
//     "id": "12",
//     "no_inventaire": "",
//     "designation": "Comparateur \u00e0 affichage digital",
//     "dim_mm_1": "0",
//     "dim_mm_2": "10",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "Pour mesure sur support vertical",
//     "emplacement": "Tiroir 4\/ABCD4",
//     "etat": "Neuf",
//     "login": "cp-jeg",
//     "status": "Emprunt\u00e9"
//   },
//   {
//     "id": "13",
//     "no_inventaire": "",
//     "designation": "Comparateur \u00e0 affichage digital",
//     "dim_mm_1": "0",
//     "dim_mm_2": "10",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "Pour mesure sur support vertical",
//     "emplacement": "Tiroir 4\/ABCD4",
//     "etat": "Neuf",
//     "login": "cp-jeg",
//     "status": "Emprunt\u00e9"
//   },
//   {
//     "id": "14",
//     "no_inventaire": "",
//     "designation": "Support \u00e0 base magn\u00e9tique",
//     "dim_mm_1": "0",
//     "dim_mm_2": "0",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "Pour comparateur",
//     "emplacement": "Tiroir 4\/BC1",
//     "etat": "Usag\u00e9",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "15",
//     "no_inventaire": "",
//     "designation": "Pinule de centrage",
//     "dim_mm_1": "6",
//     "dim_mm_2": "0",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "",
//     "emplacement": "Tiroir 4\/B2",
//     "etat": "Neuf",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "16",
//     "no_inventaire": "",
//     "designation": "Centreur de diam\u00e8tre",
//     "dim_mm_1": "2",
//     "dim_mm_2": "120",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "",
//     "emplacement": "Tiroir 4\/A2",
//     "etat": "Usag\u00e9",
//     "login": "",
//     "status": "Emprunt\u00e9"
//   },
//   {
//     "id": "17",
//     "no_inventaire": "",
//     "designation": "Clinom\u00e8tre",
//     "dim_mm_1": "0",
//     "dim_mm_2": "0",
//     "dim_angle_1": "0",
//     "dim_angle_2": "180",
//     "complement": "Avec niveau \u00e0 bulle",
//     "emplacement": "Tiroir 4\/D23",
//     "etat": "Neuf",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "18",
//     "no_inventaire": "",
//     "designation": "Bo\u00eete de cales \u00e9talon",
//     "dim_mm_1": "1",
//     "dim_mm_2": "100",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "Qualit\u00e9 0",
//     "emplacement": "Tiroir 4\/AB56",
//     "etat": "Usag\u00e9",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "19",
//     "no_inventaire": "",
//     "designation": "Jeu de jauges d'angles",
//     "dim_mm_1": "0",
//     "dim_mm_2": "0",
//     "dim_angle_1": "10",
//     "dim_angle_2": "170",
//     "complement": "",
//     "emplacement": "Tiroir 4\/C23",
//     "etat": "Usag\u00e9",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "20",
//     "no_inventaire": "",
//     "designation": "Lunette de centrage",
//     "dim_mm_1": "0",
//     "dim_mm_2": "0",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "Pour Fraiseuse Aciera F1",
//     "emplacement": "Tiroir 4\/C3",
//     "etat": "Neuf",
//     "login": "",
//     "status": "Disponible"
//   },
//   {
//     "id": "21",
//     "no_inventaire": "",
//     "designation": "Lunette de centrage",
//     "dim_mm_1": "0",
//     "dim_mm_2": "0",
//     "dim_angle_1": "0",
//     "dim_angle_2": "0",
//     "complement": "Pour tour SV 70",
//     "emplacement": "Tiroir 4\/C23",
//     "etat": "Neuf",
//     "login": "",
//     "status": "Disponible"
//   }
// ]''';

// // final String outilsDataMicro = '''[
// //   {
// //     designation": "Microm\u00e8tre ext\u00e9rieur
// //   },
// //   {}
// // ]''';
